services:

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.21.0
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - "7900:7900"

  firefox:
    image: selenium/node-firefox:4.21.0
    container_name: firefox-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub
      - HEADLESS=true
      - BASE_URL=https://www.google.com
      - BROWSER=chrome
      - OLLAMA_ENABLED=false
      - MCP_ENABLED=false
      - SCREENSHOT_ON_FAILURE=false
      - IMPLICIT_WAIT=10
      - EXPLICIT_WAIT=20
      - ALLURE_RESULTS_DIR=reports/allure-results
      - ANTHROPIC_API_KEY=
      - DB_URL=
    volumes:
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
    command: >
      pytest tests/api/
      -v --html=reports/docker-report.html
      --self-contained-html --tb=short

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: