[pytest]
testpaths = tests steps features
python_files = test_*.py
python_classes = Test*
python_functions = test_*

pythonpath = .

markers =
    smoke: Critical smoke tests
    regression: Full regression suite
    ui: Selenium UI tests
    api: REST API tests
    positive: Happy path
    negative: Error path
    data-driven: Data driven tests

addopts = -v --tb=short --strict-markers

log_cli = true
log_cli_level = INFO