[pytest]
testpaths = tests steps features
python_files = test_*.py
python_classes = Test*
python_functions = test_*

pythonpath = .

markers =
    smoke: Critical smoke tests
    regression: Full regression suite
    ui: Selenium UI tests
    api: REST API tests
    mobile: Appium mobile tests
    db: Database assertion tests
    positive: Happy path tests
    negative: Error path tests
    data-driven: Data driven tests
    bdd: BDD Gherkin tests

addopts = -v --tb=short --strict-markers

log_cli = true
log_cli_level = INFO