
import json
import hashlib
from pathlib import Path
from loguru import logger
from config.config import config


class RAGEngine:

    def __init__(self):
        self.collection = None
        self.ollama     = None
        self._setup()

    def _setup(self):
        try:
            import chromadb
            client = chromadb.PersistentClient(
                path=str(Path("data/rag_db"))
            )
            self.collection = client.get_or_create_collection(
                name="test_knowledge",
                metadata={"description": "Test cases and results"}
            )
            logger.success(f"RAG DB ready — {self.collection.count()} docs")
        except ImportError:
            logger.warning("ChromaDB not installed")
        except Exception as e:
            logger.error(f"RAG setup failed: {e}")

        if config.OLLAMA_ENABLED:
            try:
                import ollama
                self.ollama = ollama
                logger.info("Ollama connected for RAG")
            except ImportError:
                logger.warning("Ollama not available")

    def add_test_case(self, test_id: str, title: str,
                      description: str, tags: list = None,
                      result: str = "unknown") -> bool:
        if not self.collection:
            return False
        try:
            doc_id = hashlib.md5(
                f"{test_id}{title}".encode()
            ).hexdigest()
            self.collection.upsert(
                ids=[doc_id],
                documents=[f"{title}. {description}"],
                metadatas=[{
                    "test_id":     test_id,
                    "title":       title,
                    "tags":        json.dumps(tags or []),
                    "result":      result,
                    "description": description
                }]
            )
            logger.info(f"Added to RAG: {test_id} — {title}")
            return True
        except Exception as e:
            logger.error(f"RAG add failed: {e}")
            return False

    def search_similar(self, query: str, n_results: int = 3) -> list:
        if not self.collection or self.collection.count() == 0:
            logger.warning("RAG DB empty — seed first")
            return []
        try:
            results = self.collection.query(
                query_texts=[query],
                n_results=min(n_results, self.collection.count())
            )
            matches = []
            for i, doc in enumerate(results["documents"][0]):
                meta = results["metadatas"][0][i]
                dist = results["distances"][0][i]
                matches.append({
                    "test_id":     meta.get("test_id"),
                    "title":       meta.get("title"),
                    "description": meta.get("description"),
                    "result":      meta.get("result"),
                    "similarity":  round(1 - dist, 3),
                    "document":    doc
                })
            logger.success(f"Found {len(matches)} similar tests")
            return matches
        except Exception as e:
            logger.error(f"RAG search failed: {e}")
            return []

    def nlp_to_gherkin(self, plain_english: str) -> str:
        context = self._get_context(plain_english)
        if self.ollama and config.OLLAMA_ENABLED:
            return self._generate_gherkin_with_ai(plain_english, context)
        return self._generate_gherkin_template(plain_english)

    def _get_context(self, query: str) -> str:
        similar = self.search_similar(query, n_results=2)
        if not similar:
            return ""
        lines = ["Similar existing tests:"]
        for t in similar:
            lines.append(f"- {t['test_id']}: {t['title']} ({t['result']})")
        return "\n".join(lines)

    def _generate_gherkin_with_ai(self, description: str,
                                   context: str) -> str:
        prompt = f"""You are a BDD expert. Convert this to a Gherkin feature file:

"{description}"

{context}

Write a complete .feature file with Feature, 2-3 Scenarios using Given/When/Then.
Return ONLY the Gherkin content, nothing else."""

        try:
            response = self.ollama.chat(
                model=config.OLLAMA_MODEL,
                messages=[{"role": "user", "content": prompt}]
            )
            gherkin = response["message"]["content"].strip()
            logger.success("Gherkin generated by Ollama AI!")
            return gherkin
        except Exception as e:
            logger.error(f"AI Gherkin failed: {e}")
            return self._generate_gherkin_template(description)

    def _generate_gherkin_template(self, description: str) -> str:
        return f"""Feature: {description.title()}
  As a user
  I want to {description.lower()}
  So that the system works correctly

  @positive @smoke
  Scenario: Happy path
    Given the application is open
    When I perform the action correctly
    Then the result should be successful

  @negative
  Scenario: Error path
    Given the application is open
    When I use invalid data
    Then an error message should be displayed

  @data-driven
  Scenario Outline: Data driven test
    Given the application is open
    When I use "<input>"
    Then I should see "<expected>"

    Examples:
      | input   | expected |
      | valid   | success  |
      | invalid | error    |
"""

    def seed_from_existing_tests(self):
        test_cases = [
            ("TC001", "Google opens successfully",
             "Verify Google homepage loads with correct title",
             ["smoke", "ui"]),
            ("TC002", "Search box is visible",
             "Verify search input is displayed on Google",
             ["smoke", "ui"]),
            ("TC003", "Search works correctly",
             "Type query and verify results page loads",
             ["smoke", "ui"]),
            ("TC004", "Faker generates valid user",
             "DataFactory creates user with valid email",
             ["smoke"]),
            ("TC005", "Get all users API",
             "JSONPlaceholder returns 10 users with 200 status",
             ["api", "smoke"]),
            ("TC006", "Create post API",
             "POST request creates new post returns 201",
             ["api"]),
            ("TC007", "Delete post API",
             "DELETE request removes post returns 200",
             ["api"]),
            ("TC008", "User schema validation",
             "API response contains all required fields",
             ["api"]),
            ("TC009", "BDD Google search",
             "Gherkin scenario for searching on Google",
             ["bdd", "ui"]),
            ("TC010", "Data driven search from Excel",
             "Multiple search topics from Excel all succeed",
             ["data-driven"]),
        ]
        count = 0
        for tc_id, title, desc, tags in test_cases:
            if self.add_test_case(tc_id, title, desc, tags, "passed"):
                count += 1
        logger.success(f"Seeded RAG DB with {count} test cases!")
        return count

    def get_stats(self) -> dict:
        if not self.collection:
            return {"error": "RAG not initialized"}
        return {
            "total_docs": self.collection.count(),
            "db_path":    "data/rag_db",
            "ai_enabled": bool(self.ollama)
        }